apiVersion: v1
kind: Pod
metadata:
  name: dummybird
  annotations:
    k8s.v1.cni.cncf.io/networks: cni100
spec:
  containers:
  - name: bird
    image: ssasso/dummybird
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]

